// Video Composition Configuration (Auto-generated by scripts/sync-scenes.mjs)

export const SCENES = [
  {
    id: "Scene01-HookDepressiveConcept",
    name: "Scene 01: Hook - Depressive Concept",
    from: 0,
    durationInFrames: 120, // 4 seconds @ 30fps
  },
  {
    id: "Scene02-BiologicalMalfunctionSplit",
    name: "Scene 02: Biological Malfunction blueprint",
    from: 120,
    durationInFrames: 180, // 6 seconds @ 30fps
  },
  {
    id: "Scene03-DiseaseCoveredStickman",
    name: "Scene 03: Stickman Covered with Disease",
    from: 300,
    durationInFrames: 60, // 2 seconds @ 30fps
  },
  {
    id: "Scene04-SpectrumTenXMarksToBrain",
    name: "Scene 04: Digital Spectrum & Brain Connection",
    from: 360,
    durationInFrames: 150, // 5 seconds @ 30fps
  },
  {
    id: "Scene05-ZoomBrokenNeuronToWrongPill",
    name: "Scene 05: Zoom Broken Neuron to Wrong Pill",
    from: 510,
    durationInFrames: 120, // 4 seconds @ 30fps
  },
  {
    id: "Scene06-PillsIntoContainer",
    name: "Scene 06: Pills Zoom Out & Funnel Into Container",
    from: 630,
    durationInFrames: 90, // 3 seconds @ 30fps
  },
  {
    id: "Scene07-StickmanGoesCrazy",
    name: "Scene 07: Stickman Goes Crazy",
    from: 720,
    durationInFrames: 90, // 3 seconds @ 30fps
  },
  {
    id: "Scene08-MagnifyingGlassNeurons",
    name: "Scene 08: Magnifying Glass Over Neurons",
    from: 810,
    durationInFrames: 90, // 3 seconds @ 30fps
  },
  {
    id: "Scene09-DepressionTypesWheel",
    name: "Scene 09: 10 Types of Depression Wheel",
    from: 900,
    durationInFrames: 120, // 4 seconds @ 30fps
  },
  {
    id: "Scene10-MajorDepressiveDisorder",
    name: "Scene 10: Major Depressive Disorder",
    from: 1020,
    durationInFrames: 120, // 4 seconds @ 30fps
  },
  {
    id: "Scene11-ClinicalBaseline",
    name: "Scene 11: Clinical Baseline",
    from: 1140,
    durationInFrames: 60, // 2 seconds @ 30fps
  },
  {
    id: "Scene12-NeurologicalShutdown",
    name: "Scene 12: Neurological Shutdown",
    from: 1200,
    durationInFrames: 158, // 5.3 seconds @ 30fps
  },
  {
    id: "Scene13-LossOfPleasure",
    name: "Scene 13: Loss of Pleasure (Anhedonia)",
    from: 1358,
    durationInFrames: 120, // 4 seconds @ 30fps
  },
  {
    id: "Scene15-Anhedonia",
    name: "Scene 15: The Diagnosis Stamp",
    from: 1478,
    durationInFrames: 90, // 3 seconds @ 30fps
  },
  {
    id: "Scene16-CognitiveSlowdown",
    name: "Scene 16: Cognitive Slowdown (The Tar Pit)",
    from: 1568,
    durationInFrames: 91, // 3 seconds @ 30fps
  },
  {
    id: "Scene17-CrushingFatigue",
    name: "Scene 17: Profound Crushing Fatigue (The Giant Steel Ball & Chain)",
    from: 1659,
    durationInFrames: 104, // 3.5 seconds @ 30fps
  },
  {
    id: "Scene18-AcuteEpisodicSwitch",
    name: "Scene 18: Acute and Episodic (The Heavy Mechanical Switch)",
    from: 1763,
    durationInFrames: 128, // 4.3 seconds @ 30fps
  },
  {
    id: "Scene19-SharpViolentBreak",
    name: "Scene 19: Sharp, Violent Break from Baseline",
    from: 1891,
    durationInFrames: 130, // 4.3 seconds @ 30fps
  },
  {
    id: "Scene20-TemporaryCoat",
    name: "Scene 20: Temporary Layer (The Heavy Grey Winter Coat)",
    from: 2021,
    durationInFrames: 120, // 4 seconds @ 30fps
  },
];

export const TOTAL_DURATION_IN_FRAMES = 7066; // Total audio duration (235.53s @ 30fps)
