// Master Scene Barrel Export (Auto-generated by scripts/sync-scenes.mjs)
import { Scene01_HookDepressiveConcept } from "./Scene01_HookDepressiveConcept";
import { Scene02_BiologicalMalfunctionSplit } from "./Scene02_BiologicalMalfunctionSplit";
import { Scene03_DiseaseCoveredStickman } from "./Scene03_DiseaseCoveredStickman";
import { Scene04_SpectrumTenXMarksToBrain } from "./Scene04_SpectrumTenXMarksToBrain";
import { Scene05_ZoomBrokenNeuronToWrongPill } from "./Scene05_ZoomBrokenNeuronToWrongPill";
import { Scene06_PillsIntoContainer } from "./Scene06_PillsIntoContainer";
import { Scene07_StickmanGoesCrazy } from "./Scene07_StickmanGoesCrazy";
import { Scene08_MagnifyingGlassNeurons } from "./Scene08_MagnifyingGlassNeurons";
import { Scene09_DepressionTypesWheel } from "./Scene09_DepressionTypesWheel";
import { Scene10_MajorDepressiveDisorder } from "./Scene10_MajorDepressiveDisorder";
import { Scene11_ClinicalBaseline } from "./Scene11_ClinicalBaseline";
import { Scene12_NeurologicalShutdown } from "./Scene12_NeurologicalShutdown";
import { Scene13_LossOfPleasure } from "./Scene13_LossOfPleasure";
import { Scene15_Anhedonia } from "./Scene15_Anhedonia";
import { Scene16_CognitiveSlowdown } from "./Scene16_CognitiveSlowdown";
import { Scene17_CrushingFatigue } from "./Scene17_CrushingFatigue";
import { Scene18_AcuteEpisodicSwitch } from "./Scene18_AcuteEpisodicSwitch";
import { Scene19_SharpViolentBreak } from "./Scene19_SharpViolentBreak";
import { Scene20_TemporaryCoat } from "./Scene20_TemporaryCoat";

export {
  Scene01_HookDepressiveConcept,
  Scene02_BiologicalMalfunctionSplit,
  Scene03_DiseaseCoveredStickman,
  Scene04_SpectrumTenXMarksToBrain,
  Scene05_ZoomBrokenNeuronToWrongPill,
  Scene06_PillsIntoContainer,
  Scene07_StickmanGoesCrazy,
  Scene08_MagnifyingGlassNeurons,
  Scene09_DepressionTypesWheel,
  Scene10_MajorDepressiveDisorder,
  Scene11_ClinicalBaseline,
  Scene12_NeurologicalShutdown,
  Scene13_LossOfPleasure,
  Scene15_Anhedonia,
  Scene16_CognitiveSlowdown,
  Scene17_CrushingFatigue,
  Scene18_AcuteEpisodicSwitch,
  Scene19_SharpViolentBreak,
  Scene20_TemporaryCoat,
};

export const SCENE_COMPONENTS = {
  "Scene01-HookDepressiveConcept": Scene01_HookDepressiveConcept,
  Scene01_HookDepressiveConcept: Scene01_HookDepressiveConcept,
  "Scene02-BiologicalMalfunctionSplit": Scene02_BiologicalMalfunctionSplit,
  Scene02_BiologicalMalfunctionSplit: Scene02_BiologicalMalfunctionSplit,
  "Scene03-DiseaseCoveredStickman": Scene03_DiseaseCoveredStickman,
  Scene03_DiseaseCoveredStickman: Scene03_DiseaseCoveredStickman,
  "Scene04-SpectrumTenXMarksToBrain": Scene04_SpectrumTenXMarksToBrain,
  Scene04_SpectrumTenXMarksToBrain: Scene04_SpectrumTenXMarksToBrain,
  "Scene05-ZoomBrokenNeuronToWrongPill": Scene05_ZoomBrokenNeuronToWrongPill,
  Scene05_ZoomBrokenNeuronToWrongPill: Scene05_ZoomBrokenNeuronToWrongPill,
  "Scene06-PillsIntoContainer": Scene06_PillsIntoContainer,
  Scene06_PillsIntoContainer: Scene06_PillsIntoContainer,
  "Scene07-StickmanGoesCrazy": Scene07_StickmanGoesCrazy,
  Scene07_StickmanGoesCrazy: Scene07_StickmanGoesCrazy,
  "Scene08-MagnifyingGlassNeurons": Scene08_MagnifyingGlassNeurons,
  Scene08_MagnifyingGlassNeurons: Scene08_MagnifyingGlassNeurons,
  "Scene09-DepressionTypesWheel": Scene09_DepressionTypesWheel,
  Scene09_DepressionTypesWheel: Scene09_DepressionTypesWheel,
  "Scene10-MajorDepressiveDisorder": Scene10_MajorDepressiveDisorder,
  Scene10_MajorDepressiveDisorder: Scene10_MajorDepressiveDisorder,
  "Scene11-ClinicalBaseline": Scene11_ClinicalBaseline,
  Scene11_ClinicalBaseline: Scene11_ClinicalBaseline,
  "Scene12-NeurologicalShutdown": Scene12_NeurologicalShutdown,
  Scene12_NeurologicalShutdown: Scene12_NeurologicalShutdown,
  "Scene13-LossOfPleasure": Scene13_LossOfPleasure,
  Scene13_LossOfPleasure: Scene13_LossOfPleasure,
  "Scene15-Anhedonia": Scene15_Anhedonia,
  Scene15_Anhedonia: Scene15_Anhedonia,
  "Scene16-CognitiveSlowdown": Scene16_CognitiveSlowdown,
  Scene16_CognitiveSlowdown: Scene16_CognitiveSlowdown,
  "Scene17-CrushingFatigue": Scene17_CrushingFatigue,
  Scene17_CrushingFatigue: Scene17_CrushingFatigue,
  "Scene18-AcuteEpisodicSwitch": Scene18_AcuteEpisodicSwitch,
  Scene18_AcuteEpisodicSwitch: Scene18_AcuteEpisodicSwitch,
  "Scene19-SharpViolentBreak": Scene19_SharpViolentBreak,
  Scene19_SharpViolentBreak: Scene19_SharpViolentBreak,
  "Scene20-TemporaryCoat": Scene20_TemporaryCoat,
  Scene20_TemporaryCoat: Scene20_TemporaryCoat,
};
